language: ruby
rvm:
- 2.1

install: gem install html-proofer

script: bundle install && jekyll build && htmlproof ./_site

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer